<a href="https://colab.research.google.com/github/SsemuliJoseph/Sunbird/blob/main/Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install argilla datasets huggingface_hub

Collecting argilla
  Downloading argilla-2.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.18.0)
Requirement already satisfied: httpx>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (2.12.3)
Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (4.67.3)
Requirement already satisfied: rich>=10.0.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (13.9.4)
Requirement already satisfied: pillow>=9.5.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (11.3.0)
Collecting standardwebhooks>=1.0.0 (from argilla)
  Downloading standardwebhooks-1.0.1.tar.gz (5.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.26.0->argilla) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.0.0->argilla) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.0.0->argilla) (2.20.0)
Requirement already satisfied: attrs>=21.3.0 in /usr/local/lib/python3.12/dist-packages (from standardwebhooks>=1.0.0->argilla) (26.1.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from standardwebhooks>=1.0.0->argilla) (2.9.0.post0)
Collecting Deprecated (from standardwebhooks>=1.0.0->argilla)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting types-python-dateutil (from standardwebhooks>=1.0.0->argilla)
  Downloading types_python_dateutil-2.9.0.20260518-py3-none-any.whl.metadata (1.8 kB)
Collecting types-Deprecated (from standardwebhooks>=1.0.0->argilla)
  Downloading types_deprecated-1.3.1.20260520-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub) (0.0.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.0.0->argilla) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->standardwebhooks>=1.0.0->argilla) (1.17.0)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from Deprecated->standardwebhooks>=1.0.0->argilla) (2.2.1)
Downloading argilla-2.8.0-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.3/161.3 kB 2.5 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading types_deprecated-1.3.1.20260520-py3-none-any.whl (9.1 kB)
Downloading types_python_dateutil-2.9.0.20260518-py3-none-any.whl (18 kB)
Building wheels for collected packages: standardwebhooks
  Building wheel for standardwebhooks (pyproject.toml) ... done
  Created wheel for standardwebhooks: filename=standardwebhooks-1.0.1-py3-none-any.whl size=3619 sha256=4d3a1ed6d0c5583cec5d8887d9a0eb8937b71e2895f62f91edccd713cf58ccbc
  Stored in directory: /root/.cache/pip/wheels/99/f1/9e/5875dab65df60a0e530f19d477880f0276a343e1594fb3ee5f
Successfully built standardwebhooks
Installing collected packages: types-python-dateutil, types-Deprecated, Deprecated, standardwebhooks, argilla
Successfully installed Deprecated-1.3.1 argilla-2.8.0 standardwebhooks-1.0.1 types-Deprecated-1.3.1.20260520 types-python-dateutil-2.9.0.20260518

In [ ]:
import argilla as rg
from datasets import load_dataset
from google.colab import userdata
import huggingface_hub

# 1. Securely fetch tokens from Colab Secrets
my_argilla_key = userdata.get('ARGILLA_API_KEY')
my_hf_token = userdata.get('HF_TOKEN')

# 2. Authenticate with the Hugging Face Hub
print("Authenticating with Hugging Face Hub...")
huggingface_hub.login(token=my_hf_token)

# 3. Connect to Argilla securely
client = rg.Argilla(
    api_url="https://ssemulijoseph-nlp-data-curation.hf.space",
    api_key=my_argilla_key
)

# 4. Load the REAL dataset from Hugging Face (Now authenticated!)
print("Downloading real dataset from the Hub...")
real_dataset = load_dataset("kambale/luganda-english-parallel-corpus", split="train")

# Take a sample of 100 rows to avoid overloading the free tier server
sampled_dataset = real_dataset.select(range(100))

# 5. Define the workspace structure in Argilla
settings = rg.Settings(
    fields=[
        rg.TextField(name="english", title="English Source"),
        rg.TextField(name="luganda", title="Luganda Translation")
    ],
    questions=[
        rg.LabelQuestion(
            name="quality",
            title="Is this translation accurate?",
            labels=["Yes", "No", "Needs Editing"]
        ),
        rg.TextQuestion(
            name="correction",
            title="If incorrect, provide the right translation:",
            required=False
        )
    ]
)

# 6. Create the dataset on the server and push the records
dataset = rg.Dataset(
    name="real_luganda_curation_v1",
    settings=settings,
    client=client,
)
dataset.create()

# Log the data into the Argilla UI
dataset.records.log(sampled_dataset)
print("Success! Authenticated pipeline complete and data pushed.")

Authenticating with Hugging Face Hub...
Downloading real dataset from the Hub...

luganda-english-parallel-corpus.json:   0%|          | 0.00/4.22M [00:00<?, ?B/s]

luganda-english-parallel-corpus.jsonl:   0%|          | 0.00/3.55M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/50012 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/argilla/datasets/_resource.py:264: UserWarning: Workspace not provided. Using default workspace: argilla id: 55679cb5-eb9f-4d31-8301-3706449c2f13
  warnings.warn(f"Workspace not provided. Using default workspace: {workspace.name} id: {workspace.id}")
/usr/local/lib/python3.12/dist-packages/argilla/records/_io/_datasets.py:265: UserWarning: Record id column not found in Hugging Face dataset. Using row index and split for record ids.
  warnings.warn(

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

DatasetRecords: The provided batch size 256 was normalized. Using value 100.

Sending records...: 100%|██████████| 1/1 [00:02<00:00,  2.02s/batch]

Success! Authenticated pipeline complete and data pushed.

In [ ]:
!pip install transformers[torch] datasets evaluate sacrebleu accelerate sentencepiece

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: transformers[torch] in /usr/local/lib/python3.12/dist-packages (5.10.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (1.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (4.67.3)
Requirement already satisfied: torch>=2.4 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2.11.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.1.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4->transformers[torch]) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.4->transformers[torch]) (12.8.90)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[torch]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.4->transformers[torch]) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers[torch]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers[torch]) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.8 MB/s eta 0:00:00
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu, evaluate
Successfully installed colorama-0.4.6 evaluate-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [ ]:
import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)
import evaluate
import numpy as np

# 1. Hardware Check (Ensure this prints "Using device: cuda" now!)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 2. Configurations & Model Selection
MODEL_CHECKPOINT = "facebook/nllb-200-distilled-600M"
SOURCE_LANG = "eng_Latn"
TARGET_LANG = "lug_Latn"
MAX_LENGTH = 128

# 3. Load and Split the Real Dataset
print("Loading dataset splits...")
raw_dataset = load_dataset("kambale/luganda-english-parallel-corpus", split="train")

dataset_split = raw_dataset.train_test_split(test_size=200, train_size=2000, seed=42)
train_dataset = dataset_split["train"]
eval_dataset = dataset_split["test"]

# 4. Initialize the Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT, src_lang=SOURCE_LANG, tgt_lang=TARGET_LANG)

# 5. Fixed Preprocessing & Tokenization Function
def preprocess_function(examples):
    inputs = examples["english"]
    targets = examples["luganda"]

    # Industrial Approach: Use text_target directly instead of the old context manager
    model_inputs = tokenizer(
        inputs,
        text_target=targets,
        max_length=MAX_LENGTH,
        truncation=True
    )

    return model_inputs

print("Tokenizing datasets...")
tokenized_train = train_dataset.map(preprocess_function, batched=True, remove_columns=train_dataset.column_names)
tokenized_eval = eval_dataset.map(preprocess_function, batched=True, remove_columns=eval_dataset.column_names)

# 6. Load the Pre-trained Model
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT).to(device)

# 7. Define Evaluation Metric (BLEU Score)
metric = evaluate.load("sacrebleu")

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]
    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]

    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 placeholders so we can safely decode the text labels
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    return {"bleu": result["score"]}

# 8. Data Collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

# 9. Set Industrial Training Arguments
# 9. Set Industrial Training Arguments (Fixed for latest Transformers API)
training_args = Seq2SeqTrainingArguments(
    output_dir="./nllb-luganda-baseline",
    eval_strategy="epoch",    # <-- CHANGED FROM evaluation_strategy TO eval_strategy
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=1,
    num_train_epochs=1,
    predict_with_generate=True,
    fp16=torch.cuda.is_available(),
    logging_steps=50,
    report_to="none"
)

# 10. Initialize the Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_eval,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# 11. Start Training
print("Starting training loop...")
trainer.train()

print("Evaluation results:")
print(trainer.evaluate())

Using device: cuda
Loading dataset splits...
Tokenizing datasets...

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

Starting training loop...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Evaluation results:

{'eval_loss': 1.528900146484375, 'eval_bleu': 14.643843889642923}

In [ ]:
!pip install argilla

Collecting argilla
  Downloading argilla-2.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (2.12.3)
Requirement already satisfied: huggingface_hub>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (1.18.0)
Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (4.67.3)
Requirement already satisfied: rich>=10.0.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (13.9.4)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (4.0.0)
Requirement already satisfied: pillow>=9.5.0 in /usr/local/lib/python3.12/dist-packages (from argilla) (11.3.0)
Collecting standardwebhooks>=1.0.0 (from argilla)
  Downloading standardwebhooks-1.0.1.tar.gz (5.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (3.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->argilla) (6.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.26.0->argilla) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.26.0->argilla) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.22.0->argilla) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.22.0->argilla) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.22.0->argilla) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.22.0->argilla) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.6.0->argilla) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.0.0->argilla) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.0.0->argilla) (2.20.0)
Requirement already satisfied: attrs>=21.3.0 in /usr/local/lib/python3.12/dist-packages (from standardwebhooks>=1.0.0->argilla) (26.1.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from standardwebhooks>=1.0.0->argilla) (2.9.0.post0)
Collecting Deprecated (from standardwebhooks>=1.0.0->argilla)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting types-python-dateutil (from standardwebhooks>=1.0.0->argilla)
  Downloading types_python_dateutil-2.9.0.20260518-py3-none-any.whl.metadata (1.8 kB)
Collecting types-Deprecated (from standardwebhooks>=1.0.0->argilla)
  Downloading types_deprecated-1.3.1.20260520-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (3.14.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.0.0->argilla) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.0.0->argilla) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.0.0->argilla) (2.5.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.22.0->argilla) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.22.0->argilla) (0.0.4)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from Deprecated->standardwebhooks>=1.0.0->argilla) (2.2.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.0.0->argilla) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.0.0->argilla) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->standardwebhooks>=1.0.0->argilla) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.0.0->argilla) (1.24.2)
Downloading argilla-2.8.0-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.3/161.3 kB 6.5 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading types_deprecated-1.3.1.20260520-py3-none-any.whl (9.1 kB)
Downloading types_python_dateutil-2.9.0.20260518-py3-none-any.whl (18 kB)
Building wheels for collected packages: standardwebhooks
  Building wheel for standardwebhooks (pyproject.toml) ... done
  Created wheel for standardwebhooks: filename=standardwebhooks-1.0.1-py3-none-any.whl size=3619 sha256=aa78f99fd620a61793082dac02f0481be77f9ffa6c667ce23588be35ac5df3b5
  Stored in directory: /root/.cache/pip/wheels/99/f1/9e/5875dab65df60a0e530f19d477880f0276a343e1594fb3ee5f
Successfully built standardwebhooks
Installing collected packages: types-python-dateutil, types-Deprecated, Deprecated, standardwebhooks, argilla
Successfully installed Deprecated-1.3.1 argilla-2.8.0 standardwebhooks-1.0.1 types-Deprecated-1.3.1.20260520 types-python-dateutil-2.9.0.20260518

In [ ]:
import argilla as rg
from google.colab import userdata
# from datasets import load_dataset # Removed as it's not used for this loading method

# 1. Connect to your Space securely
my_api_key = userdata.get('ARGILLA_API_KEY')
client = rg.Argilla(
    api_url="https://ssemulijoseph-nlp-data-curation.hf.space",
    api_key=my_api_key
)

# 2. Load the dataset from Argilla directly into a Hugging Face Dataset format
print("Loading dataset from Argilla into Hugging Face Dataset format...")
# Use client.datasets() to retrieve the Argilla dataset object (v2 style),
# then convert its records to a Hugging Face Dataset using .records.to_datasets()
argilla_dataset_v2_object = client.datasets(name="real_luganda_curation_v1")
hf_backed_up_dataset = argilla_dataset_v2_object.records.to_datasets()

# 3. The dataset is now a Hugging Face Dataset, which can be iterated directly
records = hf_backed_up_dataset

# 4. Filter and check how many you have actually answered
# For a Hugging Face Dataset loaded from Argilla, 'quality.responses' is a column.
# We check if this column exists and has non-empty values (i.e., has been annotated).
# Using str() and checking length to account for potential string representations of lists.
completed_annotations = [r for r in records if r.get('quality.responses') is not None and len(str(r.get('quality.responses'))) > 2]
print(f"Total Dataset Rows: {len(records)}")
print(f"Human Curated Rows: {len(completed_annotations)}")

# 5. The hf_backed_up_dataset is already in Hugging Face Dataset format.

# 6. Save a local backup file inside Colab just in case
hf_backed_up_dataset.to_csv("argilla_luganda_backup.csv")
print("Local CSV backup saved inside Colab files!")

# Optional: Push it to your private HF profile as an ultimate safeguard
# hf_backed_up_dataset.push_to_hub("your-username/luganda-clean-gold-standard", private=True)

Loading dataset from Argilla into Hugging Face Dataset format...
Total Dataset Rows: 100
Human Curated Rows: 7

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Local CSV backup saved inside Colab files!

In [ ]:
import argilla as rg
from google.colab import userdata

# 1. Connect to your Space securely
my_api_key = userdata.get('ARGILLA_API_KEY')
client = rg.Argilla(
    api_url="https://ssemulijoseph-nlp-data-curation.hf.space",
    api_key=my_api_key
)

# 2. Retrieve the Argilla v2 dataset object
print("Connecting to your Argilla dataset...")
dataset = client.datasets(name="real_luganda_curation_v1")

# 3. Export the records directly into a Hugging Face Dataset format
print("Pulling records and converting to Hugging Face Dataset format...")
hf_backed_up_dataset = dataset.records.to_datasets()

# 4. Check your curation progress
total_rows = len(hf_backed_up_dataset)
print(f"Total Dataset Rows pulled: {total_rows}")

# 5. Save a local backup file inside Colab just in case
hf_backed_up_dataset.to_csv("argilla_luganda_backup.csv")
print("🎉 Success! Local CSV backup saved inside Colab files.")

# Optional: Push it to your private HF profile as an ultimate safeguard
# hf_backed_up_dataset.push_to_hub("your-username/luganda-clean-gold-standard", private=True)

Connecting to your Argilla dataset...
Pulling records and converting to Hugging Face Dataset format...
Total Dataset Rows pulled: 100

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

🎉 Success! Local CSV backup saved inside Colab files.

In [ ]:
import pandas as pd
import json

# Load the backup CSV
df = pd.read_csv("argilla_luganda_backup.csv")

# Filter for rows where a human response exists
# In Argilla v2 exports, responses are stored as JSON strings or lists
df_clean = df[df['quality.responses'].notna()]

print(f"Verified rows with human annotations: {len(df_clean)}")
if len(df_clean) > 0:
    # Display the English source, Luganda translation, and your quality rating
    print(df_clean[['english', 'luganda', 'quality.responses']].head())

Verified rows with human annotations: 7
                                              english  \
5   Where can we get good resistant varieties that...
19  Every Monday  farmers are given advice on coff...
25  Farmers are given a platform to ask any agricu...
35  Farming programs aired on radio help farmers t...
41   Maize leaf rust causes the tip of a leaf to dry.

                                              luganda quality.responses
5   Tusobola kuggya wa ebika ebirungi ebigumira em...           ['Yes']
19   Buli Mande abalimi bawabulwa ku nnima y'emmwanyi           ['Yes']
25  Abalimi baweebwa omwagaanya okubuuza ekibuuzo ...           ['Yes']
35  Pulogulaamu z'ebyobulimi eziweerezebwa ku laad...           ['Yes']
41  Okumyukirira kw'ebikoola bya kasooli kireetera...           ['Yes']

In [ ]:
import pandas as pd
import ast

def extract_golden_dataset(csv_path):
    df = pd.read_csv(csv_path)

    clean_pairs = []

    for idx, row in df.iterrows():
        # Check if the row has been reviewed by a human
        if pd.isna(row['quality.responses']):
            continue

        try:
            # Safely convert the string representation of a list back to a real list
            quality_list = ast.literal_eval(row['quality.responses'])
            quality = quality_list[0] if quality_list else "No"
        except (ValueError, SyntaxError):
            continue

        english_text = row['english']

        # Strategy 1: If it's perfect, take the original Luganda translation
        if quality == "Yes":
            luganda_text = row['luganda']
            clean_pairs.append({"english": english_text, "luganda": luganda_text, "source": "human_verified"})

        # Strategy 2: If it needed edits, extract your manual human correction
        elif quality == "Needs Editing":
            if pd.notna(row['correction.responses']):
                try:
                    correction_list = ast.literal_eval(row['correction.responses'])
                    luganda_text = correction_list[0] if correction_list else row['luganda']
                    clean_pairs.append({"english": english_text, "luganda": luganda_text, "source": "human_corrected"})
                except (ValueError, SyntaxError):
                    continue

        # Strategy 3: If you marked it "No" (completely unsalvageable), we drop it entirely
        elif quality == "No":
            continue

    return pd.DataFrame(clean_pairs)

# Execute the extraction
golden_df = extract_golden_dataset("argilla_luganda_backup.csv")

print(f"📊 Golden Dataset Size: {len(golden_df)} rows")
print("---")
if not golden_df.empty:
    print(golden_df[['english', 'luganda', 'source']].head())

📊 Golden Dataset Size: 7 rows
---
                                             english  \
0  Where can we get good resistant varieties that...
1  Every Monday  farmers are given advice on coff...
2  Farmers are given a platform to ask any agricu...
3  Farming programs aired on radio help farmers t...
4   Maize leaf rust causes the tip of a leaf to dry.

                                             luganda          source
0  Tusobola kuggya wa ebika ebirungi ebigumira em...  human_verified
1   Buli Mande abalimi bawabulwa ku nnima y'emmwanyi  human_verified
2  Abalimi baweebwa omwagaanya okubuuza ekibuuzo ...  human_verified
3  Pulogulaamu z'ebyobulimi eziweerezebwa ku laad...  human_verified
4  Okumyukirira kw'ebikoola bya kasooli kireetera...  human_verified